//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find_My_Friend_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationHistory
    {
        public int LocationId { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<System.DateTime> RecordedAt { get; set; }
    
        public virtual User User { get; set; }
    }
}
