//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Find_My_Friend_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.LocationHistories = new HashSet<LocationHistory>();
            this.LocationRequests = new HashSet<LocationRequest>();
            this.LocationRequests1 = new HashSet<LocationRequest>();
        }
    
        public int UserId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PhoneNo { get; set; }
        public string ProfileImage { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual ICollection<LocationHistory> LocationHistories { get; set; }
        public virtual ICollection<LocationRequest> LocationRequests { get; set; }
        public virtual ICollection<LocationRequest> LocationRequests1 { get; set; }
    }
}
